Django-Project/inventory/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = 'inventory'
urlpatterns = [
    url('', views.index, name='index'),
]

Django-Project/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views
urlpatterns = [
    path('accounts/login/', views.login_user, name= 'login_user'),
    url('inventory', include('inventory.urls',namespace = 'inventory')),
    url('login_user/', views.login_user, name= 'login_user'),
    url('logoutView/', views.logoutView, name= 'logoutView'),
    path('', views.index, name= 'index'),
    path('admin/', admin.site.urls),
    
]

Django-Project/inventory/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models




class Barang(models.Model):
    kode_barang = models.CharField(max_length=5)
    nama_barang = models.CharField(max_length=10)
    satuan = models.CharField(max_length=3)

    class Meta:
        managed = False
        db_table = 'barang'


class BarangBackup(models.Model):
    kode_barang = models.CharField(max_length=5)
    nama_barang = models.CharField(max_length=10)
    qty = models.IntegerField()
    kategory = models.CharField(max_length=15)

    class Meta:
        managed = False
        db_table = 'barang_backup'


class HistoryPenjualan(models.Model):
    kode_transaksi_pembelian = models.CharField(max_length=5)
    kode_barang = models.CharField(max_length=5)
    qty = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'history_penjualan'


class Penjualan(models.Model):
    kode_transaksi = models.IntegerField()
    kode_barang = models.ForeignKey(Barang, models.DO_NOTHING, db_column='kode_barang')
    qty = models.IntegerField()
    status_history = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'penjualan'


class TransaksiPembelian(models.Model):
    kode_transaksi = models.CharField(max_length=5, blank=True, null=True)
    kode_barang = models.ForeignKey(Barang, models.DO_NOTHING, db_column='kode_barang', blank=True, null=True)
    qty = models.IntegerField(blank=True, null=True)
    stok = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'transaksi_pembelian'

Django-Project/inventory/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='/accounts/login/')
def index(request):
    return render(request, 'inventory/index.html')

Django-Project/mysite/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.shortcuts import redirect

# Create your views here.

def index(request):
    context = {
        'link':"logout", 
        'inventory':'inventory',   
    }
    if not request.user.is_authenticated:
       return redirect('login_user')

    return render(request, 'index.html', context)

def login_user(request):
    contect = {
        'page_title': 'Please sign in'
    }
    user = None
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            return redirect('inventory/')
   
        else:
            return redirect('login_user')
    else:
        # return redirect('index')
        return render(request, 'login.html', contect)


@login_required(login_url='/accounts/login/')
def logoutView(request):
	context = {
		'page_title':'logout'
	}

	if request.method == "POST":
		# if request.POST['logout'] == 'Submit':
		logout(request)

		return redirect('index')
        	


	return render(request, 'logout.html', context)

Django-Project/inventory/templates/inventory/index.html
{% extends "base.html" %}
{% load static %}

{% block home %}
    
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">PT. SANKYO INDONESIA</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="{% url 'logoutView' %}">Sign out</a>
    </li>
  </ul>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="#">
              <span data-feather="home"></span>
              Dashboard
            </a>
          </li>
        </ul>

        <ul class="nav flex-column">
          <li>
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Dokumen Masuk</span>
              <a class="link-secondary" href="#" aria-label="Add a new report">
                <span data-feather="minus-circle"></span>
              </a>
            </h6>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              Dokumen BC 2.3
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              Dokumen BC 4.0
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              Dokumen BC 2.6.2
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Dokumen Keluar</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="minus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              Dokumen BC 4.1
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              Dokumen BC 2.6.1
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              Dokumen BC 2.7 Out
            </a>
        </ul>
      </div>
    </nav>


    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group me-2">
            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar"></span>
            This week
          </button>
        </div>
      </div>

      <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

      <h2>Section title</h2>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>#</th>
              <th>Header</th>
              <th>Header</th>
              <th>Header</th>
              <th>Header</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>1,001</td>
              <td>Lorem</td>
              <td>ipsum</td>
              <td>dolor</td>
              <td>sit</td>
            </tr>
            <tr>
              <td>1,002</td>
              <td>amet</td>
              <td>consectetur</td>
              <td>adipiscing</td>
              <td>elit</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>Integer</td>
              <td>nec</td>
              <td>odio</td>
              <td>Praesent</td>
            </tr>
            <tr>
              <td>1,003</td>
              <td>libero</td>
              <td>Sed</td>
              <td>cursus</td>
              <td>ante</td>
            </tr>
            <tr>
              <td>1,004</td>
              <td>dapibus</td>
              <td>diam</td>
              <td>Sed</td>
              <td>nisi</td>
            </tr>
            <tr>
              <td>1,005</td>
              <td>Nulla</td>
              <td>quis</td>
              <td>sem</td>
              <td>at</td>
            </tr>
            <tr>
              <td>1,006</td>
              <td>nibh</td>
              <td>elementum</td>
              <td>imperdiet</td>
              <td>Duis</td>
            </tr>
            <tr>
              <td>1,007</td>
              <td>sagittis</td>
              <td>ipsum</td>
              <td>Praesent</td>
              <td>mauris</td>
            </tr>
            <tr>
              <td>1,008</td>
              <td>Fusce</td>
              <td>nec</td>
              <td>tellus</td>
              <td>sed</td>
            </tr>
            <tr>
              <td>1,009</td>
              <td>augue</td>
              <td>semper</td>
              <td>porta</td>
              <td>Mauris</td>
            </tr>
            <tr>
              <td>1,010</td>
              <td>massa</td>
              <td>Vestibulum</td>
              <td>lacinia</td>
              <td>arcu</td>
            </tr>
            <tr>
              <td>1,011</td>
              <td>eget</td>
              <td>nulla</td>
              <td>Class</td>
              <td>aptent</td>
            </tr>
            <tr>
              <td>1,012</td>
              <td>taciti</td>
              <td>sociosqu</td>
              <td>ad</td>
              <td>litora</td>
            </tr>
            <tr>
              <td>1,013</td>
              <td>torquent</td>
              <td>per</td>
              <td>conubia</td>
              <td>nostra</td>
            </tr>
            <tr>
              <td>1,014</td>
              <td>per</td>
              <td>inceptos</td>
              <td>himenaeos</td>
              <td>Curabitur</td>
            </tr>
            <tr>
              <td>1,015</td>
              <td>sodales</td>
              <td>ligula</td>
              <td>in</td>
              <td>libero</td>
            </tr>
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>


{% endblock home %}

Django-Project/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>DOKUMEN PABEAN</title>

    {% include "snippets/styles.html" %}

</head>

<body>
    {% block home %}

    {% endblock home %}

    {% include "snippets/js.html" %}


</body>

</html>

Django-Project/templates/index.html
{% block header %}
 <a href="{% url 'logoutView' %}">{{ link }}</a>

<h1>Selamat datang ini adalah halaman utama.</h1>
<h3>Halo: {{user}}</h3>

<a href="{% url 'inventory:index' %}">{{ inventory }}</a>
{% endblock header %}

Django-Project/templates/login.html
{% extends "base.html" %}
{% load static %}

{% block home %}
<main class="form-signin">
  <form method="POST">
    {% csrf_token %}
    <h1 class="h3 mb-3 fw-normal">{{page_title}}</h1>
    <label for="username" class="visually-hidden">Username: </label>
    <input type="text" name="username" id="username" class="form-control" placeholder="User Name" required autofocu>
    <br>
    <label for="password" class="visually-hidden">Password: </label>
    <input type="password" name="password" id="password" class="form-control" placeholder="Password" required>
    <br>
    <button type="submit">Login</button>
  </form>
</main>

{% endblock home %}

Django-Project/templates/logout.html
<!DOCTYPE html>
<html>
<head>
	<title>{{page_title}}</title>
</head>
<body>
	<h1>{{page_title}}</h1>

	<p>Apakah anda yakin akan logout?</p>

	<form method="POST">
		{% csrf_token %}
		<input type="submit" name="logout" value="Iya">
		<input type="submit" name="cancle" value="Tidak">
	</form>
</body>
</html>

Django-Project/templates/snippets/js.html
{% load static %}
<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script> -->
<!-- <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script> -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/dashboard.js' %}"></script>

Django-Project/templates/snippets/styles.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/dashboard.css' %}">
<link rel="stylesheet"  type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">